### ISSUE TITLE
通信部のデータの仕様を決める

### ISSUE THREAD

**Issue by sho0126hiro** [meister2018-prism/shiwori#1]

**Comment by Akari000** [comment]
必要そうなのは
・ユーザーデータ
・読み始めの時間
・送信時間のタイムスタンプ（終わりの時間）
・ページ数
・本の整理番号か何か　←ハードの使用で変わりそう
timestampは自動でできるんだっけ...

**Comment by sho0126hiro** [comment]
comment test

**Comment by sho0126hiro** [comment]
#143 に加えて、新たな通信部の設計も終わりました
