### ISSUE TITLE
データベースサーバーを構築する

### ISSUE THREAD

**Issue by sho0126hiro** [meister2018-prism/shiwori#14]

**Comment by sun-yryr** [comment]
テーブルの中身を決めてテストデータを埋めておきたいです

**Comment by sun-yryr** [comment]
## user table ユーザ情報のデータベース
- **id (primary)** 識別番号（変更不可）
- **name** 名前
- **introduction** 自己紹介
- **createdate** アカウント取得日
- **devices** 接続デバイスid (null)
- **updatedate** 最終更新日

## 統計のtable
- **userid** 誰の統計情報か
- **allreadtime** 総読書時間
- **allreadbooks** 総読書数
- **speed** 平均読書スピード
- **YYYY-MM-readtime** YYYY年MM月の読書時間 (0 or null)
- **YYYY-MM-readbooks** YYYY年MM月の読書数 (上)
- **YYYY-MM-speed** YYYY年MM月の平均スピード (上)

## records table 感想のデータベース
- **id (primary)** 識別番号（変更不可）
- **userid** 感想書いた人
- **username** 感想書いた人の名前
- **isbn** international standard book number
- **impression** 感想 ( "" )
- **star** 星の数
- **readtime** 読書時間
- **readspeed** 分速ページ数
- **time** 更新時間

## bookmark table ブックマーク管理のデータベース
- **id (primary)** 識別番号（変更不可）
- **userid** ブックマークした人
- **username** ブックマークした人の名前
- **isbn** international standard book number
- **page** ページ番号
- **memo** メモ ( "" )
- **time** 更新時間
