### ISSUE TITLE
ページ遷移・ファイル構成をまとめる

### ISSUE THREAD

**Issue by Akari000** [meister2018-prism/shiwori#23]

**Comment by sho0126hiro** [comment]
Component 
Header : ナビ
Footer :  Home Search MyPageに飛ぶ
graph : rechart.js
本棚ページ
本棚ランキング付き

# ページ遷移

## WelcomePage 
- logo(Title)
コンポーネントの表示切替
  - login
  - login 他のアカウントから。
- tutorial >> Home

## Home 
Welcomeには戻れない
component  : graph
share
平均ページ数などの情報
- データ修正ページ（入力）

## Search
-Keyword
  searchBox
  - 検索 >> 本棚ページ
- CodeScan
カメラ起動
-カテゴリ一覧
    - 本棚ページ（ランキング順）
    - 本の詳細
-オススメの本三つ表示
  - Details

##  MyPage
-Profile
  -BookMark
    - 本の詳細
  - 本棚ページ（最近読んだ本）
グラフ
- プロフィール編集（headerに）
↑この三つはフッターから移動できる

## SubMenues(ハンバーガー)
 -Setting
 -Help
 -Contact
 - review
 - login 
 - out
 - tutorial

**Comment by sho0126hiro** [comment]
- asset
  - json
   - img
- component
  - Graph
    - pieGraph.js
    - barGraph.js
  - books.js
  - Header.js
  - Footer.js
  - Logo.js

- Screen
    - Welcome
      - welcomeScreen.js
      - pageScreen.js
      - tutorialScreen.js 
    - Home
       - HomeScreen.js
       - EditScreen.js
    - Search
      - SearchScreen.js
      - CategroryScean.js
      - CodeScanScreen.js
      - KeywordScreen.js
    - MyPage
        - MyPageScreen.js
        - BookMarkScreen.js
    - Hunbarg
        - HumbargScreen.js
        - SettingScreen.js
        - HelpScreen.js
        - ContactScreen.js

**Comment by sho0126hiro** [comment]
https://meister2018-prism.slack.com/archives/CF3JDK9MJ/p1546179024000700

**Comment by Akari000** [comment]
ナビゲーションの仕様について

## 以下の３つのナビゲーションを使用
Drawer navigation
Stack navigation
Tab navigation


## それぞれの役割
Drawer navigation : ハンバーガーメニュー（サブメニュー）の表示
Tab navigation :タブメニュー（ 画面下にある「ホーム」「検索」「マイページ」）の遷移
Stack navigation : 上記２つ以外の遷移（ボタン遷移など）

## ハンバーガーメニュー
画面右上のハンバーガーアイコンを押した際以下の項目を表示する．
ここで使うscreenはどこからでもアクセス可能にするため，「タブメニュー」に記載する各Stack に全て追加している．

1. 設定
2. ヘルプ
3. コンタクト
4. レビュー
5. ログインorログアウト

詳細
（ Shiwori/shiwori_app/src/Drawer.js ）

　1.設定　
SettingScreen に遷移
アカウント情報の設定はここで行う（未実装）
2. ヘルプ
HelpScreen に遷移
使い方の説明を記載する（未実装）
3. コンタクト
ContactScreenに遷移
4. レビュー
レビュー専用URLに飛ばし，端末のデフォルトブラウザで開くようにする
（遷移先のURLは未定）
  5. ログインorログアウト
ユーザーのログイン状況に応じてどちらかを表示．（未実装）

ログイン：loginScreen に遷移
ログアウト : ログアウトし，welcomeScreen に遷移．再度ログインの仕方を選んでもらう



## タブメニュー
タブメニューは常に画面下に表示され，この遷移では再読込はされない
タブメニューは以下の項目を表示する

1. ホーム
2. 検索
3. マイページ

詳細
（ Shiwori/shiwori_app/src/Tab.js ）
3つの項目から遷移できるスクリーンをそれぞれ事前に，homeStack, SearchStack, MypageStackとして設定している．

1. ホーム
homeStackに登録されたスクリーンを表示する．
最初はHomeScreen を表示，それ以降は最後に観覧したスクリーンを表示する．

HomeStack
・Home: HomeScreen 読書記録のグラフ，最近読んだ本を表示
・Edit: EditScreen 読書記録の編集画面
・Details: DetailsScreen 本の詳細

2. 検索
SearchStackに登録されたスクリーンを表示する．
最初はSearchScreen を表示，それ以降は最後に観覧したスクリーンを表示する．

SearchStack
・Search : SearchScreen 検索方法の選択画面
・Keyword: KeywordsScreen キーワード検索
・Category: CategoryScreen カテゴリー検索
・CodeScan: CodeScanScreen バーコードスキャン検索
・Ranking: RankingScreen 本のランキング
・Details: DetailsScreen 本の詳細
・Books: BooksScreen 本一覧（本棚）
・BookMark: BookMarkScreen ブックマーク一覧
・BookMarkDetails: BookMarkDetailsScreen ブックマークの詳細
・BookMarkRegister : BookMarkRegisterScreen ブックマーク登録画面
3. マイページ
MypageStackに登録されたスクリーンを表示する．
最初はMyPageScreen を表示，それ以降は最後に観覧したスクリーンを表示する．

MyPageStack
・MyPage: MyPageScreen マイページ（プロフィール，最近読んだ本，読書記録を表示）
・Details: DetailsScreen 本の詳細
・Books: BooksScreen 本一覧（本棚）
・BookMark: BookMarkScreen ブックマーク一覧
・BookMarkDetails: BookMarkDetailsScreen ブックマークの詳細　
・BookMarkRegister : BookMarkRegisterScreen ブックマーク登録画面

## その他のスクリーン遷移
以下のスクリーン遷移はスタックナビゲーションを使用する

1. welcomeScreen  
2. LoginScreen,
3. TutorialScreen

タブナビゲーションと同じ深さでこの３つのスクリーンの遷移をする（未実装）
（ここせつめいが難しい）

## 修正が必要な箇所
・HomeStack   Detail->Detailsに名前変更
・HomeStack   BookMark: BookMarkScreen の追加
・DetailScreen が残っている場合はファイルを削除
・src/Tab.js  HamburgerStackの削除

**Comment by sho0126hiro** [comment]
Bookmark登録画面を追加しました
