### ISSUE TITLE
ページごとにAPIorDBから取得するデータについてまとめる

### ISSUE THREAD

**Issue by sho0126hiro** [meister2018-prism/shiwori#43]
#14 #23

**Comment by sho0126hiro** [comment]
# shiworiApp 画面ごとに取得するデータまとめ
前提と、アプリ側のメモ
```
    Appに保存されたユーザーＩＤを用いてDBの統計・感想・ブックマークテーブルの内容を取得する。
    ページ遷移をする中で、データをそのまま移行できるため、前画面で取得したデータは、遷移後にも使得るようにします。（したい）
    （例：本棚一覧で取得した本の画像リンクは、詳細ページに飛んでも、再び画像リンクを取得する必要はないです。）
    ただし、以下には重複するデータも含め全部列挙しています。
```
# 重要
`読んだページ数を手入力して、DBにセットするページが存在しない`
 追記：グラフの編集で、できるようにします
`ブックマークの入力、DBにセットするページが存在しない`
追記：ブックマーク追加ページを追加しました。
---
# ページ遷移　目次
*クリックでジャンプできます*

起動 >> HOME
* [起動画面](#startup)
* [ログイン画面](#login)
* [チュートリアル](#startup-tutorial)

MAIN
* [HOME](#home)
    * [グラフの編集](#editChart)
    * [サブメニュー（ハンバーガー）](#subMenues)
        * [レビュー](#review)
        * [ログイン](#subMenues-login)
        * [ログアウト](#subMenues-logout)
        * [チュートリアル](#subMenues-tutorial)
* [Search（検索・登録）](#search)
    * [キーワード検索画面](#key)
        * [検索結果本棚ページ](#searchBookList)
            * [本の詳細](#BookDetails)
                * [登録画面](#regist)
                    * [ブックマーク追加画面](#bookmark)

    * [バーコードリーダー](#barcode)
        * [本の詳細](#BookDetails)
            * [登録画面](#regist)
                    * [ブックマーク追加画面](#bookmark)

    * [カテゴリ一覧](#ctgry)
        * [検索結果本棚ページ](#searchBookList)
            * [本の詳細](#BookDetails)
                * [登録画面](#regist)
                    * [ブックマーク追加画面](#bookmark)

* [MyPage](#mypage)
    * [最近読んだ本（本棚ページ）](#recent)
        * [本の詳細](#recentBookDetails)
            * [ブックマーク一覧](#recentBookMarkList)
                * [ブックマーク詳細](#recentBookMarkDetails)
    * [プロフィール編集](#editProfile)
    * [ブックマーク一覧](#BookMarkList)
        * [ブックマーク詳細](#BookMarkDetails)


<a id="startup"></a>

## 起動画面
- user_id（ログイン判定）
- user_update_date (最終更新日：最終更新日から時間たちすぎてたら再ログイン？)

<a id="login"></a>

## ログイン画面
- ログイン回りちょっとわかんない
- user_email　を set
- user_password を set

<a id="startup-tutorial"></a>

## チュートリアル
- なし

---
<a id="home"></a>

## HOME
- 以下、グラフ表示のため
    （グラフ表示：過去(?)[年/週/月]間を表示するか決めてない）
    - 日付ごとの読んだ本の数
    - 月ごとの読んだ本の数
    - 読んだページ数の平均（DBからの取得か、Appで算出するか）

<a id="editChart"></a>

### HOME >> グラフの編集
- データセットのため、取得情報はなし

<a id="SubMenues"></a>

### HOME >> SubMenues(ハンバーガー)
- なし

<a id="review"></a>

#### HOME >> SubMenues >> Review
- なし

<a id="subMenues-login"></a>

#### HOME >> SubMenues >> ログイン
- アプリ側ユーザー情報をセット

<a id="subMenues-logout"></a>

#### HOME >> SubMenues >> ログアウト
- アプリ側メールアドレスなどユーザー情報のクリア

<a id="subMenues-tutorial"></a>

#### HOME >> SubMenues >> turorial
- なし

<a id="search"></a>

## Search(探す・登録)
オススメの本を表示する。そのために必要な情報
- 最近読んだ本の著者情報
- 最近読んだ本のジャンル
とかを取得できればOK?

<a id="key"></a>

### Search >> キーワード検索画面
- なし

<a id="barcode"></a>

### Search >> バーコードリーダー
- なし

<a id="ctgry"></a>

### Search >> カテゴリ一覧
- なし

<a id="searchBookList"></a>

### Search共通：検索結果本棚ページ
GoogleBooksAPI(?)で取得したデータを表示する

- 表紙画像
- 本の名前（文字数には表示上、上限を設けるかも）
- 著者

<a id="BookDetails"></a>

### Search共通：検索結果本棚ページ >> 本の詳細
GoogleBooksAPI(?)で取得したデータを表示する

- 表紙画像
- 本の名前
- 著者名
- 出版社
- 他ユーザーの評価（できれば）
- 購入リンク（できれば）
- 他に何かあれば

<a id="regist"></a>

### Search共通：検索結果本棚ページ >> 本の詳細 >> 登録画面
- DBセット

<a id="bookmark"></a>



### Search共通：本の詳細 >> 登録 >> ブックマーク追加ページ
- ブックマークに追加する。
- 追加項目
  - ページ数
  - memo

<a id="myPage"></a>

## MyPage
- user_id
- user_name
- user_introduction 自己紹介
- 最近読んだ本：3 or 4冊分
    - 表紙画像
    - 本のタイトル
    - 著者名

- allreadtime : 総読書時間
- allreradbooks : 総読書数
- speed 平均読書スピード
- 以下、グラフ表示のため
    - 読書時間
    - 読書数
    - 平均スピード

<a id="recent"></a>

### MyPage >> 最近読んだ本（本棚ページ）
こっちは最近読んだ本の本の数の上限はない。
(ロードが長くなりそうなので、一度に表示する本の数は制限する.)
最近読んだ本のデータをDBから取得 >>

GoogleBooksAPI(?)で取得したデータを表示する

- 表紙画像
- 本の名前（文字数には表示上、上限を設けるかも）
- 著者

<a id="recentBookDetails"></a>

### MyPage >> 最近読んだ本 >> 本の詳細
GoogleBooksAPI(?)で取得したデータを表示する
- 表紙画像
- 本の名前
- 著者名
- 出版社
- 自分の評価・感想
- 自分の星の数
- 読んだページ数
- 本のページ数 >> 読了率を算出して、グラフ表示をしたい
- この本の分速ページ数（いる？）

<a id="recentBookMarkList"></a>

### MyPage >> 最近読んだ本 >> 本の詳細 >> ブックマーク一覧
- 対象の本に対するブックマークのページ数
- ページ数に対するブックマーク（文字数制限付き）

<a id="recentBookMarkDetails"></a>

### MyPage >> 最近読んだ本 >> 本の詳細 >> ブックマーク一覧 >> ブックマーク詳細
- ブックマークのページ数
- ブックマーク（全文）
- 更新時間：表示する（？）

<a id="editProfile"></a>

### MyPage >> プロフィール編集
- DBの以下の情報を書き換える
- user_name
- user_introduction

<a id="#BookMarkList"></a>

### MyPage >> ブックマーク一覧
- ブックマークが存在する本のタイトル
- ブックマークが存在する本の著者名
- その本にあるブックマークのページ数

<a id="#BookMarkDetails"></a>

### MyPage >> ブックマーク一覧 >> ブックマーク詳細
- 対象の本のタイトル
- ページ数
- ブックマーク（全文）

**Comment by sun-yryr** [comment]
ログイン周りについて
ヘッダーに `キー: X-SHIWORI-Signature   値:prismprism` を設定（値は仮）

## 会員登録（URL: ）
ボディに `user_name, email, password` を入れてpostリクエストを送ると登録できる。
responseは
```
{
  "userinfo": {
    "name": "ゆるゆる",
    "user_id": "6ba7fead-df7e-4aa2-afd8-9c3ac3a77b1a",
    "created_date": 0,
    "update_date": "2019-01-09-17:14:27",
    "email": "s15178@tokyo.kosen-ac.jp",
    "all_readtime": null,
    "all_readspeed": 0,
    "create_date": "2019-01-09-17:14:27",
    "speed": 0
  },
  "records": [],
  "bookmarks": [],
  "statistics": []
}
```

## ログイン（URL: ）
ボディに `email, password` を入れてpostリクエストを送る
responseは
```
成功
status code 200
{
  "userinfo": {
    "user_name": "ゆるゆる",
    "userid": "99d29d63-90e1-42b3-a626-47cd57b29719",
    "create_date": 1546696106,
    "update_date": 1546696263,
    "email": "s15178@tokyo.kosen-ac.jp",
    "all_readtime": 0,
    "all_readbooks": 0,
    "speed": 0
  },
  "records": [
      {
          "id": なんか,
          "user_name": 名前,
          "star": 星の数,
          "impression": 感想,
          "readtime": 読書時間,
          "readspeed": 読書スピード,
          "update_date": 更新日,
          "book": {
              "author": 作者,
              "title": タイトル,
              "imgUrl": サムネイルのurl,
              "publication": 出版社,
              "page": ページ数
          }
      }
  ],
  "bookmarks": [
      {
          "
          "id": なんか,
          "page": マークしたページ数,
          "memo": めも,
          "update_date": 更新日,
          "book": {
              "author": 作者,
              "title": タイトル,
              "imgUrl": サムネイルのurl,
              "publication": 出版社,
              "page": ページ数
          }
      }
  ],
  "statistics": [
      未定
  ]
}

失敗
status code 400
{
  "message": "e-mail or password is invalid."
}
```
これでどうかな？

---

懸念としては、ログイン時に何個のデータを返却するか？。と、続きのデータのリクエスト方法と返却方法をどうするか？。

**Comment by sho0126hiro** [comment]
ブックマーク追加ページ・データの手入力について追記しました。
