### ISSUE TITLE
react native をlocalで実行してみる

### ISSUE THREAD

**Issue by Akari000** [meister2018-prism/shiwori#9]
react native の勉強。
アンドロイドかi　phonでhello worldを実行とかやってみる

**Comment by sho0126hiro** [comment]
環境構築できました。iPhoneはExpoで実機動作確認済み、AndroidはAndroidStudioのEmulatorで実行動作確認済み（Sho)
@Akari000 もできてたらissue閉じて

**Comment by Akari000** [comment]
snackで実行したのでclose
